### ISSUE TITLE
How to Re-Paire 2.4G Wireless barcode scanner (SS890/SS898) with the receiver?

### ISSUE THREAD

**Issue by BEVOLINK** [BEVOLINK/Barcode-Scanner#1]
Step 1: Download CHSET from https://raw.githubusercontent.com/BEVOLINK/Barcode-Scanner/master/Manual/2.4G%20Wireless%20Barcode%20Scanner%20SS890(NeoCode).pdf and print it. 
Step 2:  pull out the receiver from computer (compatible with HID) USB port;
Step 3:  push the receiver into your computer USB port;

Then you will have 15 seconds to Re-paire the Scanner with the receiver;  the step 4,5,6 MUST be finished in 15 seconds, otherwise please repeat from step 2 to 6.

Step 4:  Find section A "CHSET" in the downloaded document, Scan the setting code “CHSET”; 
Step 5:  Scan “1” or “0” of the “ Setting Conference” in the section C;
Step 6:  Scan any one of the “0” to “9” of the “ Setting Conference”;

That is OK!
You have succeed Re-pairing your barcode scanner, you can scan the code you want to read and the digit will display on the screen of your computer or other device.

**Comment by soontornvp** [comment]
Hi,

Could you please show me how to re-pair the ss898 able to scan the barcode on the file that attached, pls see attached file at the following links,
![20150926_155613_soi chaloem khet 4](https://cloud.githubusercontent.com/assets/14848051/10116763/2c231a64-6469-11e5-8ae3-44e617b5022e.jpg)

thanks,
Soontornvp
